# Copyright (c) 2018, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
script:

- echo -e "\033[36m${DOWNLOAD_LOCATION}/${DOWNLOAD_CHANNEL}/${BALLERINA_VERSION}${RC:-}/${DISTRIBUTION_NAME}${RC:-}.zip\033[m"
- wget https://wso2.org/jenkins/view/All%20Builds/job/products/job/product-microgateway/lastSuccessfulBuild/artifact/distribution/target/wso2am-micro-gw-toolkit-3.0.0-beta3-SNAPSHOT.zip

- unzip -q wso2am-micro-gw-toolkit-3.0.0-beta3-SNAPSHOT.zip

- export PATH=${PATH}:$(pwd)/wso2am-micro-gw-toolkit-3.0.0-beta3-SNAPSHOT/bin

- ballerina version

- ballerina build 1_demo_hello.bal

- ballerina build 2_demo_annotations.bal

- ballerina build 3_demo_connector.bal

- ballerina build 4_demo_transformations.bal

- ballerina build 5_demo_kubernetes.bal

- ballerina build 6_demo_external_endpoint.bal

- ballerina build 7_demo_circuit_breaker.bal

- ballerina build 8_demo_async.bal

