[docker]
  [docker.dockerConfig]
    enable = true
    name = 'employees'
    registry = 'nuwanbando'
    tag = 'v1'
    #buildImage = ''
    #dockerHost = ''
    #dockerCertPath = ''
    #baseImage = ''
    #enableDebug = ''
    #debugPort = ''
    #push = ''
    #username = ''
    #password = ''
  [docker.dockerCopyFiles]
    enable = true
    [[docker.dockerCopyFiles.files]]
        source = "/home/travis/build/nuwanbando/cnip-catalog/gateways/wso2-micro-gw/passthrough/wso2am-micro-gw-toolkit-3.0.0-beta2/resources/conf/micro-gw.conf"
        target = '/home/ballerina/conf/micro-gw.conf'
        isBallerinaConf = true
[kubernetes]
  [kubernetes.kubernetesDeployment]
    enable = false
    name = 'employees-svc'
    #labels = ''
    #replicas = ''
    #enableLiveness = ''
    #initialDelaySeconds = ''
    #periodSeconds = ''
    #livenessPort = ''
    #imagePullPolicy = ''
    image = 'nuwanbando/employees:v1'
    #env = ''
    #buildImage = 'nuwanbando/employees'
    [kubernetes.kubernetesDeployment.copyFiles]
        enable = true
        [[kubernetes.kubernetesDeployment.copyFiles.files]]
            source = '/Users/nuwanbando/dev/trunk/micro-gw/toolkit/wso2am-micro-gw-toolkit-3.0.0-beta2/resources/conf/micro-gw.conf'
            target = '/home/ballerina/conf/micro-gw.conf'
            isBallerinaConf = true
    #dockerHost = ''
    #dockerCertPath = ''
    #push = ''
    #username = ''
    #password = ''
    #baseImage = ''
    #singleYAML = ''
  [kubernetes.kubernetesService]
    enable = false
    name = 'employees-svc'
    #labels = ''
    serviceType = 'NodePort'
    #port = ''
  [kubernetes.kubernetesIngress]
    enable = false
    name = 'employees-svc'
    #labels = ''
    hostname = 'nuwanbando.com'
    #annotations = ''
    path = '/'
    #targetPath = ''
    #ingressClass = ''
  [kubernetes.secureKubernetesIngress]
    enable = false
    #name = ''
    #labels = ''
    #hostname = ''
    #annotations = ''
    #path = ''
    #targetPath = ''
    #ingressClass = ''
  [kubernetes.kubernetesHpa]
    enable = false
    #name = ''
    #labels = ''
    #minReplicas = ''
    #maxReplicas = ''
    #cpuPrecentage = ''
  [kubernetes.kubernetesSecret]
    enable = false
    #name = ''
    #mountPath = ''
    #readOnly = ''
    #data = ''
  [kubernetes.kubernetesConfigMap]
    enable = false
    ballerinaConf = 'path/to/micro-gw.conf'
    #[[kubernetes.kubernetesConfigMap.configMaps]]
    #    name = ''
    #    mountPath = ''
    #    readOnly = false
    #    data = ['']
  [kubernetes.kubernetesPersistentVolumeClaim]
    enable = false
    #name = ''
    #mountPath = ''
    #readOnly = ''
    #accessMode = ''
    #volumeClaimSize = ''
  [kubernetes.kubernetesJob]
    enable = false
    #name = ''
    #labels = ''
    #restartPolicy = ''
    #backoffLimit = ''
    #activeDeadlineSeconds = ''
    #schedule = ''
    #imagePullPolicy = ''
    #image = ''
    #env = ''
    #buildImage = ''
    #dockerHost = ''
    #dockerCertPath = ''
    #push = ''
    #username = ''
    #password = ''
    #baseImage = ''