openapi: "3.0.0"
servers:
- url: http://empdir-nuwanbando.herokuapp.com
info:
  version: 1.0.0
  title: Swagger Employees
  license:
    name: MIT
x-mgw-basePath: /v2
x-mgw-production-endpoints:
  urls:
  - http://empdir-nuwanbando.herokuapp.com
x-auth-type: None
x-throttling-tier: Unlimited
paths:
  /employees:
    get:
      summary: List all employees
      operationId: listEmployees
      tags:
        - employees
      responses:
        200:
          description: A paged array of employees
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employees"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /employees/{employeeId}:
    get:
      summary: Info for a specific employee
      operationId: showEmployeeById
      tags:
        - Employee
      parameters:
        - name: employeeId
          in: path
          required: true
          description: The id of the employee to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employees"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Employee:
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
        lastname:
          type: string
        title:
          type: string
    Employees:
      type: array
      items:
        $ref: "#/components/schemas/Employee"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string