on:
  issues: {types: reopened}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const opts = github.issues.listForRepo.endpoint.merge({
              ...context.issue,
              number: context.issue.number
            })
            
            console.log(opts)
