on:
  issues: {types: opened}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.projects.createCard({...context.issue, column_id: 7472347, 
                                                          content_id: context.issue.issue_number, 
                                                          content_type: 'issue'})
