on:
  issues: {types: reopened}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('test: '+ context.payload.issue.id)
            github.projects.createCard({...context.issue, column_id: 7472347, 
                                                          content_id: context.payload.issue.id, 
                                                          content_type: 'issue'})
                                                          
