on:
  issues: {types: opened}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: '👋 Thanks for reporting!'})
            github.issues.addLabels({...context.issue, labels: ['Triage']})
            github.projects.createCard({...context.project, column_id: 7472347, 
                                                          content_id: context.issue.number, 
                                                          content_type: 'Issue'})
